---
info:
  title: mqtt_memfault_attributes
attributes:
  - name: memfault_transport
    summary: "Publish Memfault data using selected transport (so that it can be forwarded)"
    required: true
    schema:
      maximum: 3
      minimum: 0
      type: integer
      enum:
        NONE: 0
        HTTP: 1
        MQTT: 2
        COAP: 3
    x-ctype: uint8_t
    x-default: 1
    x-readable: true
    x-savable: true
    x-writable: true
  - name: mqtt_memfault_topic
    summary: Topic for publishing Memfault data
    required: true
    schema:
      maxLength: 255
      type: string
    x-ctype: string
    x-default: ""
    x-savable: true
    x-writable: true
    x-readable: true
  - name: coap_mflt_proxy_route
    summary: Route used when publishing Memfault data to CoAP proxy
    required: true
    schema:
      maxLength: 32
      type: string
    x-ctype: string
    x-default: "memfault"
    x-savable: true
    x-writable: true
    x-readable: true
  - name: store_memfault_data
    summary: Flag to indicate whether memfault data should be stored to file or posted
    required: true
    schema:
      type: integer
    x-ctype: bool
    x-default: 0
    x-savable: true
    x-writable: true
    x-readable: true
