/**
 * @file lcz_sensor_event.h
 * @brief Sensor event types for Laird Connectivity Bluetooth sensors.
 *
 * Copyright (c) 2020 Laird Connectivity
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef __LCZ_SENSOR_EVENT_H__
#define __LCZ_SENSOR_EVENT_H__

/******************************************************************************/
/* Includes                                                                   */
/******************************************************************************/
#include <zephyr.h>
#include <zephyr/types.h>

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/* Global Constants, Macros and Type Definitions                              */
/******************************************************************************/
typedef enum MAGNET_STATE { MAGNET_NEAR = 0, MAGNET_FAR } MagnetState_t;

typedef enum SensorEventType {
	SENSOR_EVENT_RESERVED = 0,
	SENSOR_EVENT_TEMPERATURE = 1,
	SENSOR_EVENT_MAGNET = 2, /* or proximity */
	SENSOR_EVENT_MOVEMENT_START = 3,
	SENSOR_EVENT_ALARM_HIGH_TEMP_1 = 4,
	SENSOR_EVENT_ALARM_HIGH_TEMP_2 = 5,
	SENSOR_EVENT_ALARM_HIGH_TEMP_CLEAR = 6,
	SENSOR_EVENT_ALARM_LOW_TEMP_1 = 7,
	SENSOR_EVENT_ALARM_LOW_TEMP_2 = 8,
	SENSOR_EVENT_ALARM_LOW_TEMP_CLEAR = 9,
	SENSOR_EVENT_ALARM_DELTA_TEMP = 10,
	SENSOR_EVENT_ALARM_TEMPERATURE_RATE_OF_CHANGE = 11,
	SENSOR_EVENT_BATTERY_GOOD = 12,
	SENSOR_EVENT_ADV_ON_BUTTON = 13,
	SENSOR_EVENT_NON_CONSECUTIVE = 14, /* Generated by gateway */
	SENSOR_EVENT_IMPACT = 15,
	SENSOR_EVENT_BATTERY_BAD = 16,
	SENSOR_EVENT_RESET = 17,
	/* BT6x */
	SENSOR_EVENT_TEMPERATURE_1 = 18,
	SENSOR_EVENT_TEMPERATURE_2 = 19,
	SENSOR_EVENT_TEMPERATURE_3 = 20,
	SENSOR_EVENT_TEMPERATURE_4 = 21,
	SENSOR_EVENT_VOLTAGE_1 = 22,
	SENSOR_EVENT_VOLTAGE_2 = 23,
	SENSOR_EVENT_VOLTAGE_3 = 24,
	SENSOR_EVENT_VOLTAGE_4 = 25,
	SENSOR_EVENT_CURRENT_1 = 26,
	SENSOR_EVENT_CURRENT_2 = 27,
	SENSOR_EVENT_CURRENT_3 = 28,
	SENSOR_EVENT_CURRENT_4 = 29,
	SENSOR_EVENT_PRESSURE_1 = 30,
	SENSOR_EVENT_PRESSURE_2 = 31,
	SENSOR_EVENT_ULTRASONIC_1 = 32,
	SENSOR_EVENT_TEMPERATURE_ALARM = 33,
	SENSOR_EVENT_ANALOG_ALARM = 34,
	SENSOR_EVENT_DIGITAL_ALARM = 35,
	SENSOR_EVENT_EPOCH = 36,
	SENSOR_EVENT_RESET_V2 = 37,
	SENSOR_EVENT_TAMPER = 38,

	SENSOR_EVENT_MOVEMENT_END = 39,

	NUMBER_OF_SENSOR_EVENTS
} SensorEventType_t;
BUILD_ASSERT(sizeof(SensorEventType_t) == 1, "Sensor Event enum too large");

/** NRF52 reset events from a sensor
 * (not the same as reset reason register bitmasks)
 */
typedef enum SensorResetEvent {
	RESET_EVENT_POWER_UP = 0,
	RESET_EVENT_RESETPIN,
	RESET_EVENT_DOG,
	RESET_EVENT_SREQ,
	RESET_EVENT_LOCKUP,
	RESET_EVENT_OFF,
	RESET_EVENT_LPCOMP,
	RESET_EVENT_DIF,
	RESET_EVENT_NFC,
	RESET_EVENT_VBUS,
	RESET_EVENT_UNKNOWN,

	NUMBER_OF_RESET_EVENTS
} SensorResetEvent_t;
BUILD_ASSERT(sizeof(SensorResetEvent_t) == 1, "Unexpected size");

/* The IG60 publishes events with these names and a voltage or temperature. */
#define IG60_GENERATED_EVENT_STR_BATTERY_GOOD "batteryGood"
#define IG60_GENERATED_EVENT_STR_BATTERY_BAD "batteryBad"
#define IG60_GENERATED_EVENT_STR_ALARM_HIGH_TEMP_1 "alarmHighTemp1"
#define IG60_GENERATED_EVENT_STR_ALARM_HIGH_TEMP_2 "alarmHighTemp2"
#define IG60_GENERATED_EVENT_STR_ALARM_HIGH_TEMP_CLEAR "alarmHighTempClear"
#define IG60_GENERATED_EVENT_STR_ALARM_LOW_TEMP_1 "alarmLowTemp1"
#define IG60_GENERATED_EVENT_STR_ALARM_LOW_TEMP_2 "alarmLowTemp2"
#define IG60_GENERATED_EVENT_STR_ALARM_LOW_TEMP_CLEAR "alarmLowTempClear"
#define IG60_GENERATED_EVENT_STR_ALARM_DELTA_TEMP "alarmDeltaTemp"
#define IG60_GENERATED_EVENT_STR_ADVERTISE_ON_BUTTON "advertiseOnButton"

/* This is the format in the sensor event log for the BT510.
 *
 * Salt is used internally by BT510 Sensor Log to differentiate
 * events with the same timestamp.
 */
typedef struct __attribute__((packed)) SensorEventBt510 {
	uint32_t timestamp;
	union __attribute__((packed)) {
		uint16_t u16;
		uint8_t magnetState;
		int16_t temperatureCc;
		uint16_t batteryMv;
	} data;
	SensorEventType_t type;
	uint8_t salt;
} SensorEventBt510_t;
BUILD_ASSERT(sizeof(SensorEventBt510_t) == 8, "Sensor event NOT packed");

typedef union __attribute__((packed)) SensorEventData {
	uint32_t u32;
	int32_t s32;
	float f;
	struct {
		uint16_t u16;
		uint16_t reserved;
	};
} SensorEventData_t;

typedef struct __attribute__((packed)) SensorEvent {
	uint32_t timestamp;
	SensorEventData_t data;
	SensorEventType_t type;
	uint8_t salt;
	uint8_t reserved1;
	uint8_t reserved2;
} SensorEvent_t;
BUILD_ASSERT(sizeof(SensorEvent_t) == 12, "Sensor event NOT packed");

/******************************************************************************/
/* Global Function Prototypes                                                 */
/******************************************************************************/
/**
 * @retval Reset reason code as a string (enumerated type from sensor).
 */
const char *lcz_sensor_event_get_reset_reason_string(uint8_t code);

#ifdef __cplusplus
}
#endif

#endif /* __LCZ_SENSOR_EVENT_H__ */
